name: Build website
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Hydrogen'
          cache: 'npm'

      - run: npm install
      - name: Build with Next.js
        env:
          PUBLIC_URL: https://jorgev259.github.io/lucius-chat-yap
        run: |
          npm run build
          touch .build/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
